### ISSUE TITLE
Error message when reset password is used is generic

### ISSUE THREAD

**Issue by NebojshaBobo** [scalefocus/photopixels#93]
When password is changed via the reset password option in the Edit Users pane, and if an admin user sets non valid password (ex. abcabc), the system throws generic 400 error message, instead of a descriptive one.

Actual:

![Image](https://github.com/user-attachments/assets/6fc5b929-6cdc-40c9-bc79-b99f6090678d)

Expected (the text is a suggestion):

![Image](https://github.com/user-attachments/assets/71e573b6-df41-4f76-b798-32a5cfd2f779)

**Comment by NebojshaBobo** [comment]
@kolev-sf  please add the naming convention agreed in the group for Name field in Create user tab, renaming it in Username.

![Image](https://github.com/user-attachments/assets/48b68680-12d9-41ae-bd2b-ebabbd4428c8)

![Image](https://github.com/user-attachments/assets/10846659-d94e-4cd4-9360-396976882252)

**Comment by NebojshaBobo** [comment]
@kolev-sf whenever user deletes media from the trash page (permanently), the error message that displays has a typo. The word permanently is written wrongly.

![Image](https://github.com/user-attachments/assets/5f713c0f-0d2d-48bf-aae0-f49cd79cdd36)

**Comment by kolev-sf** [comment]
The bug is already fixed:

![Image](https://github.com/user-attachments/assets/5f366735-08b6-4584-962d-74195b114a5c)

However, the typos that were mentioned in comments are fixed

**Comment by NebojshaBobo** [comment]
This issue is not fixed, as the system throws the generic error when new password is entered, that is not up to standards. This issue is located in the Edit user panel > Reset Password option:

![Image](https://github.com/user-attachments/assets/556af394-39a7-46c2-a20b-1e045863e3fe)

**Comment by NebojshaBobo** [comment]
Issue fixed.

<img width="987" height="765" alt="Image" src="https://github.com/user-attachments/assets/603af16d-0a5c-4dd8-9d57-b5c42568e9e0" />
